[project]
repository-type = "documentation"
versioning-scheme = "semver"
branching-model = "library-release"
release-model = "none"
primary-language = "none"

[project.co-authors]
wphillipmoore-vergil = "Co-Authored-By: wphillipmoore-vergil <285019742+wphillipmoore-vergil@users.noreply.github.com>"

[ci]
versions = ["latest"]
integration-tests = false

[dependencies]
vergil = "v2.0.13"
