name: CI

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: vergil-project/vergil-actions/.github/workflows/ci-quality.yml@v2.0
    with:
      language: shell
      versions: '["latest"]'
      container-suffix: base
      container-tag: 'latest'

  security:
    uses: vergil-project/vergil-actions/.github/workflows/ci-security.yml@v2.0
    permissions:
      contents: read
      security-events: write
    with:
      language: shell
      run-codeql: false
      container-suffix: base
      container-tag: 'latest'
